#!/bin/bash
if [ "$1" = "install" ]; then
  if [ -e $HOME/bin/$1 ]; then
    echo "Reinstalling $1"
    rm -r $HOME/bin/$1
    curl -f -O https://mkpm.github.io/packages/$1.tar.gz
    mv $1.tar.gz $HOME/bin/$1.tar.gz
    tar -xzf $HOME/bin/$1.tar.gz
    rm $HOME/bin/$1.tar.gz
  fi
elif [ "$1" = "del" ]; then
  if [ -e $HOME/bin/$1 ]; then
    rm -r $HOME/bin/$1
  fi
fi